apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash
spec:
  ports:
  - name: "25826"
    port: 25826
    targetPort: 25826
  - name: "5044"
    port: 5044
    targetPort: 5044
  - name: "5045"
    port: 5045
    targetPort: 5045
  selector:
    app: logstash
status:
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash-lb
spec:
  ports:
  - name: "25826"
    port: 25826
    targetPort: 25826
  - name: "5044"
    port: 5044
    targetPort: 5044
  - name: "5045"
    port: 5045
    targetPort: 5045
  selector:
    app: logstash
  type: LoadBalancer
status:
