apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nap
spec:
  selector:
    matchLabels:
      app: nginx-nap
  template:
    metadata:
      labels:
        app: nginx-nap
      annotations:
        version: v1.1
    spec:
      containers:
        - name: nginx-nap
          image: registryemeasa.azurecr.io/nginx/nap:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: secret-azure-acr
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nap
spec:
  type: ClusterIP
  selector:
    app: nginx-nap
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nap-external
spec:
  type: LoadBalancer
  selector:
    app: nginx-nap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
